Added PixiParser
PixiEditor/PixiEditor pull request #118
Opened 2020-12-20 15:32 UTC by CPKreuz

Implemented new [PixiParser](https://github.com/PixiEditor/PixiParser)

2020-12-20 16:26 UTC, flabbet commented
Fix tests

2020-12-20 16:42 UTC, flabbet commented
Found a bug, create a new file, size 1x1, and save. Then try to open it.
![image](https://user-images.githubusercontent.com/25402427/102718815-94bb1080-42ea-11eb-9e84-9713139bcb41.png)

2020-12-21 13:23 UTC, CPKreuz commented
Fixed in the latest commit, you just have make a NuGet package
The build in the pipeline is gonna fail

2020-12-21 17:19 UTC, flabbet requested changes
Updated package, please fix tests

2020-12-21 19:20 UTC, flabbet requested changes
Now saving a file and opening it results in the same error.

2020-12-22 17:39 UTC, flabbet commented
The first impression is good, I'll test it more a bit later

2020-12-23 10:50 UTC, flabbet requested changes
It works great, I didn't find any bugs, just small formatting changes :)

2020-12-23 10:50 UTC, flabbet commented on PixiEditor/Helpers/Extensions/ParserHelpers.cs
> +            return serializable;
You can make it shorter.

```suggestion
            Parser.SerializableDocument serializable = new Parser.SerializableDocument()
           {
               Width = document.Width;
               Height = document.Height;
               Layers = document.Layers.Select(x => x.ToSerializable()).ToArray();
               Swatches = document.Swatches.Select(x => new Tuple<byte, byte, byte, byte>(x.A, x.R, x.G, x.B)).ToArray();
            }
            return serializable;
```

2020-12-23 10:50 UTC, flabbet commented on PixiEditor/Helpers/Extensions/ParserHelpers.cs
> +            return serializable;
Same here

2020-12-23 11:21 UTC, flabbet approved these changes
👌

2020-12-23 19:36 UTC, merged