Added layer merging
PixiEditor/PixiEditor pull request #124
Opened 2020-12-27 17:50 UTC by CPKreuz

Only thing that doesn't work is undoing, I could use some help with that @flabbet 

Closes #120

2020-12-27 17:57 UTC, flabbet commented
Please write tests for your changes

2020-12-27 19:03 UTC, flabbet requested changes
I'll think of a method to implement undo, for now, add tests and change a thing I mentioned.

2020-12-27 19:03 UTC, flabbet commented on PixiEditor/Models/DataHolders/Document.cs
> +
`Document.cs` is getting too long, maybe split some methods as other partial one or extension to `Document` class

2020-12-27 19:37 UTC, CPKreuz commented
> I'll think of a method to implement undo, for now, add tests and change a thing I mentioned.

Problem is that it crashes now when undoing

2020-12-28 20:05 UTC, flabbet commented
I have an idea since we have combined layers, we need to store only BitmapPixelChanges of pixels that are gone due to merging, layer name, offset, width, height, and index, you need to save those pixels during merging

2020-12-30 18:11 UTC, flabbet commented
Or what about saving the layers as a .pixi file in the temp folder and load it on demand?

2021-02-11 13:22 UTC, flabbet requested changes
I added undo to this, but I found one behavior thing that bothers me. If you merge with below, layers get merged, but in reversed order. I don't think it should work like that

2021-02-11 13:52 UTC, CPKreuz commented
> I added undo to this, but I found one behavior thing that bothers me. If you merge with below, layers get merged, but in reversed order. I don't think it should work like that

ah shit, forgot I had to fix that

2021-02-11 17:04 UTC, flabbet approved these changes
_    
       | |   
  ___ | | __
 / _ \| |/ /
| (_) |   < 
 \___/|_|\_\

2021-02-11 17:04 UTC, merged