Undo remove layers
PixiEditor/PixiEditor pull request #136
Opened 2021-01-09 16:59 UTC by flabbet

Solves #104

Added `StorageBasedUndo` which saves selected layers on disk, and loads them on demand, as part of the Undo and Redo processes. This allows storing layers without memory leak risk. System stores layers in PNG format.

Thanks to the described solution I added Remove layer undo support.

Also wrote tests for `StorageBasedUndo`, but I didn't cover the remove layer, I'll do that tomorrow.

2021-01-09 21:29 UTC, Equbuxu reviewed
Multiple layers are displayed as selected after undoing layer removal. To replicate: make a new canvas, press new layer, right-click base layer, delete it, undo

2021-01-09 21:31 UTC, Equbuxu commented
Can't undo adding a layer

2021-01-09 21:39 UTC, CPKreuz requested changes
What @Equbuxu said

2021-01-11 07:39 UTC, CPKreuz reviewed
Seems to work

2021-01-11 07:40 UTC, CPKreuz approved these changes
Forgot to approve

2021-01-11 22:21 UTC, Equbuxu commented
Moving a layer and undoing it prevents you from undoing anything before. To replicate: make a new canvas, draw something, make a new layer, move it below the base layer, attempt to undo everything. You are stuck in an infinite loop of two layers going back and fourth

2021-01-11 22:25 UTC, Equbuxu requested changes
In some cases, two layers are selected after undoing layer removal. To replicate: make a new canvas, create 3 new layers, remove the base layer, remove layer 3, remove layer 1, undo three times.

2021-01-11 22:29 UTC, Equbuxu commented
Might be outside of the scope of this PR, but changes in layer visibility and opacity should also be undoable

2021-01-11 22:56 UTC, Equbuxu commented on PixiEditor/Models/Undo/StorageBasedChange.cs
> +            Action<object[]> fianlRedoProcess = parameters =>
typo

2021-01-11 23:04 UTC, Equbuxu commented
Move layer tool result does not get undone correctly on a layer that was deleted and later restored. To replicate: make a canvas, make a new layer, draw something on it, use the pointer tool to move the drawing somewhere, delete the layer, undo, attempt to undo again.

2021-01-14 19:36 UTC, flabbet commented
Okay, fixed the bug. I'll add layer visibility and opacity undo tomorrow

2021-01-16 09:42 UTC, flabbet commented
It should work now, I'll added IsVisible and Opacity undo, I need to write and fix tests, but you can review it now

2021-01-20 20:13 UTC, Equbuxu requested changes
Alright, I do acknowledge the fact that splitting the review into multiple messages was a stupid idea of mine, but 

this
> Moving a layer and undoing it prevents you from undoing anything before. To replicate: make a new canvas, draw something, make a new layer, move it below the base layer, attempt to undo everything. You are stuck in an infinite loop of two layers going back and fourth

and this

> In some cases, two layers are selected after undoing layer removal. To replicate: make a new canvas, create 3 new layers, remove the base layer, remove layer 3, remove layer 1, undo three times.

still needs fixing

2021-01-27 12:47 UTC, Equbuxu requested changes

2021-01-27 12:47 UTC, Equbuxu commented on PixiEditor/Models/DataHolders/Document.cs
> +                }
Sometimes ActiveLayerIndex in Document ends up with an incorrect value after undo/redo, causing a crash when trying to get ActiveLayer. I believe it is caused by SetNextLayerAsActive not firing when a layer that is not active gets deleted. For example, if there are two layers, and ActiveLayerIndex is 1, deleting layer 0 won't update the index, even though after the deletion there is obviously only 1 layer left and ActiveLayerIndex has to be at 0.
To replicate: make a canvas, make a new layer, delete base layer, undo, select layer 1, redo, attempt to draw.

2021-01-28 18:37 UTC, flabbet commented
Fixed the bug, I will make a separate issue for undoing the selection, this is outside the scope of this PR. @Equbuxu @CPKreuz I would request the review, please

2021-02-02 21:28 UTC, CPKreuz requested changes

2021-02-02 21:28 UTC, CPKreuz commented on PixiEditor/Models/Controllers/UndoManager.cs
> +                }
Fix formatting

2021-02-07 05:00 UTC, Equbuxu approved these changes

2021-02-07 12:13 UTC, merged