Avalondock theme
PixiEditor/PixiEditor pull request #145
Opened 2021-01-31 12:02 UTC by flabbet

- Redesigned AvalonDock with document previews.
- Added Layer previews
- Changed highlighted layer color
- (Hopefully) Improved performance of `CombineLayers`

2021-01-31 17:41 UTC, CPKreuz commented
I recommend making sure that the tests are passing

2021-01-31 17:43 UTC, flabbet commented
![image](https://user-images.githubusercontent.com/25402427/106392907-41ada080-63f4-11eb-8eae-0f855dda116d.png)

2021-01-31 18:21 UTC, CPKreuz requested changes
I now looked at it and I really like it

One thing I noticed is when you undock both Color Picker and Layers the docking thing is still there. Would be nice if it would collapse

<img width="1920" alt="rightNotGoingAway" src="https://user-images.githubusercontent.com/45312141/106393835-838d1580-63f9-11eb-9859-722a2ce5f81c.PNG">

2021-01-31 18:26 UTC, CPKreuz commented
In other words, why aren't we using the same DockingManager for both document and color picker/layers

2021-01-31 18:33 UTC, CPKreuz commented
Also, can you remove the corners between tabs and on the top left
And the close button is still blue

![Screenshot (5)](https://user-images.githubusercontent.com/45312141/106394092-17abac80-63fb-11eb-9623-d4a589ab785e.png)

2021-02-01 10:27 UTC, flabbet commented
I fixed one CornerRadius below the document tabs, but the rest is, for now, a little too much work. I'll do that eventually. But for now, I would prefer to focus on more important things

2021-02-01 10:56 UTC, CPKreuz requested changes
Middle Mouse button should also select the document

2021-02-01 10:56 UTC, CPKreuz commented on PixiEditor/Models/ImageManipulation/BitmapUtils.cs
> +            int height = document.Height > document.Width ? maxPreviewHeight : document.Height / (document.Width / maxPreviewWidth);
I get a `DivideByZeroException` for some images, maybe use floats for dividing

2021-02-02 20:54 UTC, CPKreuz approved these changes

2021-02-02 20:55 UTC, merged