WIP: Template layers
PixiEditor/PixiEditor pull request #150
Opened 2021-02-11 15:53 UTC by CPKreuz

Template Layers are layers that keep their original size while still being visible on the whole document, they can't be edited and will save the path to the original. Changes made to the original image will automatically be copied to the template layers.

WIP:
Serializing/Deserializing,
use Windows File Picker,
Code cleanup

2021-03-01 09:55 UTC, flabbet requested changes
It works, however, I am a bit concerned since you need to manually disable features from the Reference layers instead of enabling the ones you need. We might miss that in the future and release the reference layer with things that shouldn't be there. Can you take care of this?

2021-03-01 09:55 UTC, flabbet commented on PixiEditor/ViewModels/SubViewModels/Main/LayersViewModel.cs
> +        public void NewTemplateLayer(object parameter)
NewReferenceLayer

2021-03-01 09:55 UTC, flabbet commented on PixiEditor/ViewModels/SubViewModels/Main/LayersViewModel.cs
> +        public RelayCommand NewTemplateLayerCommand { get; set; }
NewReferenceLayerCommand

2021-03-01 11:59 UTC, CPKreuz commented
> It works, however, I am a bit concerned since you need to manually disable features from the Reference layers instead of enabling the ones you need. We might miss that in the future and release the reference layer with things that shouldn't be there. Can you take care of this? 

This almost looks like I have to rewrite the whole layer system, should I maybe just rewrite the whole project

2021-03-01 14:33 UTC, flabbet commented
Well, not really rewrite whole layers system, I guess it would be fine just to work with inheritance. We can find solution to this on discord today in the evening. But if you have idea just write it down here. It might be more work, but much more worth it. It will be much more maintainable.

2021-03-05 05:57 UTC, Equbuxu requested changes
Those two "New Layer" and "New Reference Layer" buttons take up way too much space for what they are worth, we should eventually replace them with small pictograms. This PR might be a good place for it.

When moving reference layer using pointer tool it snaps to the "big" pixel grid. This is not a giant deal but it would make more sense for it to be independent.

You can completely break a reference layer by deleting the layer and undoing the deletion. Selecting an area on a reference layer and attempting to drag around it produces a similar result if you drag violently enough. Something weird happens when using line, square, and circle tools on a reference layer.

Document-Clip Canvas seems to take the reference layer into account producing a weird effect, same with Center Content.

Crash: make a new canvas, add a reference layer, delete it, close the canvas tab

Crash: launch PixiEditor, make a canvas, add two reference layers, delete the top one, delete the remaining one. There is about 1/4 chance of a crash, I'm not sure what's causing it, might be the same reason as the previous one.

Crash: try adding a corrupted image as a reference layer

In general, I think reference layers should be better separated from the other code, such that we don't have to check if a given layer is a reference layer everywhere.

2021-03-05 06:07 UTC, CPKreuz commented
> In general, I think reference layers should be better separated from the other code, such that we don't have to check if a given layer is a reference layer everywhere.

That's what I was gonna add today

2021-03-07 18:41 UTC, closed without merging