Fixed 3 issues
PixiEditor/PixiEditor pull request #169
Opened 2021-03-24 17:19 UTC by CPKreuz

Fixes #166, #167 and #168

2021-03-24 19:23 UTC, flabbet commented on PixiEditor/Views/MainWindow.xaml.cs
> -            Close();
Where is this now?

2021-03-24 19:40 UTC, CPKreuz commented on PixiEditor/Views/MainWindow.xaml.cs
> -            Close();
It's in UpdateSubViewModel...

2021-03-25 08:15 UTC, flabbet commented
https://github.com/PixiEditor/PixiEditor/blob/master/PixiEditor/ViewModels/SubViewModels/Main/UpdateViewModel.cs#L57-L85

this is not the same as this

https://github.com/PixiEditor/PixiEditor/blob/master/PixiEditor/Views/MainWindow.xaml.cs#L93-L119

2021-03-25 08:17 UTC, flabbet requested changes
Fix the installer

2021-03-27 12:15 UTC, flabbet requested changes
Shutdown PixiEditor, open `%appdata%\PixiEditor`, change max recent files to "asdasd", open PixiEditor -> crash.

Also there is always visible restart button instead of version 
![image](https://user-images.githubusercontent.com/25402427/112720411-76bf0680-8efe-11eb-8fde-7791b02b6aea.png)

2021-03-27 12:15 UTC, flabbet commented on PixiEditor/ViewModels/SubViewModels/Main/FileViewModel.cs
> +                NoticeDialog.Show("This pixi file uses the old file format and can't be opened", "Old file format");
Maybe "This .pixi file uses the old format, which is no longer supported and can't be opened." would be better

2021-03-29 19:08 UTC, flabbet commented
While we are it, maybe add YouTube and Donate (open collective) button to the startup window? And perhaps icons?

2021-04-09 15:27 UTC, flabbet requested changes
Screenshot says it all 
![image](https://user-images.githubusercontent.com/25402427/114203823-cbc83700-9958-11eb-8445-687e936ff2f3.png)

Also, Instead of "Sponsor" maybe add "Donate"

2021-04-09 16:14 UTC, CPKreuz commented
> Screenshot says it all 
> ![image](https://user-images.githubusercontent.com/25402427/114203823-cbc83700-9958-11eb-8445-687e936ff2f3.png)
> 

I see nothing wrong here

2021-04-09 16:52 UTC, flabbet requested changes

2021-04-09 16:52 UTC, flabbet commented on PixiEditor/Views/Dialogs/HelloTherePopup.xaml
> +                            Content="Donate" ToolTip="And subscribe to PixiEditor's OnlyFans please">
I'll kick your ass one day

2021-04-09 17:15 UTC, flabbet approved these changes

2021-04-09 17:15 UTC, merged