Created MSIX package
PixiEditor/PixiEditor pull request #177
Opened 2021-04-17 15:42 UTC by CPKreuz

and fixed shortcut typo

2021-04-20 10:30 UTC, flabbet requested changes
Empty space is too big in these images
![image](https://user-images.githubusercontent.com/25402427/115381563-fa090a80-a1d3-11eb-8de2-f976c1720335.png)

Also, the splash screen is not very good. I can help you with creating these assets

2021-04-20 10:31 UTC, flabbet commented
Also, I am not sure, but shouldn't Internet be checked here? 
![image](https://user-images.githubusercontent.com/25402427/115381871-4eac8580-a1d4-11eb-800c-43cdd25a4786.png)

2021-04-20 10:33 UTC, flabbet commented
Open is safe, isn't it? 
![image](https://user-images.githubusercontent.com/25402427/115382106-96331180-a1d4-11eb-983e-d75b1b7ebc01.png)

2021-04-20 10:35 UTC, flabbet commented
Small description correction
`PixiEditor is pixel-art editing software. Create beautiful sprites for your games, animations (coming soon!) and edit images. All packed in an eye-friendly dark theme.`

2021-04-20 10:58 UTC, CPKreuz commented
If you would use the whole image it would use the whole tile wich no other app does

We also do not have to add any permission stuff (like internet) because PixiEditor is running in full trust

2021-04-20 11:01 UTC, flabbet commented
Oh all right, what about other stuff I mentioned?

2021-04-20 11:13 UTC, CPKreuz commented
> Oh all right, what about other stuff I mentioned?

Will work on that

2021-04-20 11:15 UTC, flabbet commented
Also, you should fix Azure Pipelines or at least find why is it failing

2021-04-26 10:13 UTC, flabbet commented
I fixed the pipeline, fix the tests and merge conflict

2021-04-26 13:36 UTC, flabbet commented
Also update the PixiParser package

2021-04-28 14:05 UTC, flabbet requested changes
Don't hide the startup window by clicking outside on release. I don't see a point in this

2021-04-28 14:05 UTC, flabbet commented on PixiEditor/Views/Dialogs/HelloTherePopup.xaml.cs
> +                (Assembly.GetExecutingAssembly().GetName().Version.Build != 0 ? $".{Assembly.GetExecutingAssembly().GetName().Version.Build}" : "");
You can assign `Assembly.GetExecutingAssembly().GetName()` to a variable, instead of calling the method 4 times.

2021-04-28 14:05 UTC, flabbet commented on PixiEditor/Views/MainWindow.xaml
> +            <Button Margin="1,0,0,0" Command="{Binding UndoSubViewModel.UndoCommand}" Style="{StaticResource ToolSettingsGlyphButton}" Content="&#xE7A7;"/>
Add tooltips

2021-04-28 16:18 UTC, flabbet approved these changes

2021-04-28 16:29 UTC, merged