Move Viewport tool should be always be replaced with previous tool on space key release #295
PixiEditor/PixiEditor pull request #336
Opened 2022-02-07 20:14 UTC by tomaszkot

MoveViewportTool assigned to H key.
MoveViewportTool transient on assigned to Space key.

2022-02-08 17:53 UTC, flabbet approved these changes

2022-02-09 21:11 UTC, Equbuxu requested changes
Good job, this is going in the right direction. One issue: 
1. Select Move Viewport tool manually (using mouse)
2. Move the Viewport a bit
3. Press and release middle mouse button or space

This brings up the pencil tool which was selected in the very beginning. Since the Move Viewport tool was already selected before step 3, pressing space and middle mouse button should have no effect

2022-02-09 21:49 UTC, tomaszkot commented
> Good job, this is going in the right direction. One issue:
> 
> 1. Select Move Viewport tool manually (using mouse)
> 2. Move the Viewport a bit
> 3. Press and release middle mouse button or space
> 
> This brings up the pencil tool which was selected in the very beginning. Since the Move Viewport tool was already selected before step 3, pressing space and middle mouse button should have no effect

Yes, I just fixed it.

2022-02-10 21:11 UTC, tomaszkot commented
> Looks good to me, there is a small detail I forgot about last time. There is a tooltip that has a small description of the tool when you hover your mouse over it. That description still says that the shortcut is Space instead of H. It needs to be updated manually (which kinda sucks)

Yes, I made them being read dynamically. So now there is nothing blocking such enh: #343

2022-02-11 12:39 UTC, flabbet approved these changes

2022-02-11 12:39 UTC, flabbet commented on PixiEditor/Models/Tools/Tools/MoveViewportTool.cs
> +        {
Can you make it the same way as other tools? Arrow function instead of whole `get` body?

2022-02-13 05:22 UTC, Equbuxu approved these changes

2022-02-13 10:43 UTC, merged