Add a tool size increase and decrease shortcuts using [ and ]
PixiEditor/PixiEditor pull request #42
Opened 2020-09-07 08:29 UTC by brendan-holmes

- Added new shortcut bindings for '[' and ']' in View Model with -1 and +1 parameter for decrease and increase respectively.
- Created new command 'ChangeToolsizeCommand' which executes a new method called 'ChangeToolsize'.
- Added setter for 'Toolsize' property in BitmapManager.
- 'ChangeToolsize(object parameter)' increments/decrements the current value of 'Toolsize' by the value of 'parameter' if the resultant value is > 0.

Tests:
![image](https://user-images.githubusercontent.com/57035210/92365704-8d0a9e00-f137-11ea-94ce-9d9d73b4b7ac.png)

2020-09-07 17:43 UTC, flabbet requested changes
Also, it would be awesome if the preview highlight changed in real-time, not only after moving the mouse

2020-09-07 17:43 UTC, flabbet commented on PixiEditor/Models/Controllers/BitmapManager.cs
> +                SelectedTool.Toolbar.GetSetting("ToolSize").Value = value;
Using shortcuts on the tool, which doesn't have `ToolSize` raises an error, you should add null checking on the setter.

2020-09-08 17:21 UTC, flabbet approved these changes
Awesome, now it works great

2020-09-08 20:37 UTC, brendan-holmes commented
Thanks for the review! Glad to have done my first-ever PR on this fun project!

2020-09-09 15:11 UTC, merged