Flip canvas n stuff
PixiEditor/PixiEditor pull request #434
Opened 2022-12-01 13:00 UTC by flabbet

- [x] Flip whole canvas vertically and horizontally
- [x] Flip individual layers along tight bounds center
- [x] Fixed palettes context menu
- [x] Rotate canvas
- [x] Rotate layers
- [x] Fix palette browser non-refreshing after importing palette from file

2022-12-03 14:11 UTC, CPKreuz requested changes
![image](https://user-images.githubusercontent.com/45312141/205444907-5369dba2-54b9-4534-b0ac-a7c92595079d.png)

Maybe put the flip and the rotate in seperate menus

![image](https://user-images.githubusercontent.com/45312141/205445014-00c7ac57-5f59-47af-a663-bd6bde425237.png)

Some icons would be cool

2022-12-03 21:17 UTC, CPKreuz requested changes
![image](https://user-images.githubusercontent.com/45312141/205462227-87c53c74-0470-4368-9ffd-7922fc11a34a.png)

Half of the image gets caught of after rotating the image by 90° twice

Happens with images that have a non 1:1 aspect ratio

2022-12-03 21:17 UTC, CPKreuz commented on src/PixiEditor/Views/MainWindow.xaml
> +                            <MenuItem Header="Rotate Image 270&#186;" cmds:Menu.Command="PixiEditor.Document.Rotate270Deg"/>
I feel like 270° should be written as -90° or using counter-clockwise notations

2022-12-03 21:17 UTC, CPKreuz commented on src/PixiEditor/Views/MainWindow.xaml
> +                        <MenuItem Header="_Flipping">
Maybe just `Flip` fit's more instead of `Flipping`

2022-12-04 10:24 UTC, flabbet commented
Nice catch. Fixed, please test again. I noticed masks are rotating weirdly, so it's worth keeping in mind

2022-12-04 12:19 UTC, CPKreuz approved these changes
Except for those inconsistencies in the context menu and the usage of the command attributes it looks good

2022-12-04 12:19 UTC, CPKreuz commented on src/PixiEditor/Views/MainWindow.xaml
> +                                                                            <MenuItem Header="Rotate Left" cmds:Menu.Command="PixiEditor.Document.Rotate270DegLayers"/>
```suggestion
                                                                            <MenuItem Header="Rotate 90" cmds:Menu.Command="PixiEditor.Document.Rotate90DegLayers"/>
                                                                            <MenuItem Header="Rotate 180&#186;" cmds:Menu.Command="PixiEditor.Document.Rotate180DegLayers"/>
                                                                            <MenuItem Header="Rotate -90" cmds:Menu.Command="PixiEditor.Document.Rotate270DegLayers"/>
```

2022-12-04 12:19 UTC, CPKreuz commented on src/PixiEditor/ViewModels/SubViewModels/Document/DocumentManagerViewModel.cs
> +    }
This should all be doable using two methods using for whole image and for layers using a parameter

2022-12-04 13:31 UTC, merged