Bugs and Improvements
PixiEditor/PixiEditor pull request #442
Opened 2023-01-19 21:52 UTC by CPKreuz

Changes:
* Fixed .pixi preview quality (In the exporter)
* Automatically select newly created layer
* Fixed opacity slider not updating when clicking
* Added a command for pasting a reference layer from the clipboard

2023-01-22 16:52 UTC, Equbuxu requested changes
- Infinite loading when holding down lmb on the opacity slider body and moving the mouse left and right

https://user-images.githubusercontent.com/29402050/213927045-131f4c34-9294-47db-a578-f71bfe60b33d.mp4

- The close button of commands debug window doesn't work
- The layers window makes it seem like you can drag-n-drop a file there, and you can, but only if you put it at the very and, and only if you don't have that many layers already. Would be better if you could insert a file anywhere in the layers list

2023-01-22 16:52 UTC, Equbuxu commented on src/PixiEditor/ViewModels/SubViewModels/Main/LayersViewModel.cs
> +        var surface = (data == null ? ClipboardController.GetImagesFromClipboard() : ClipboardController.GetImage(data)).First();
dispose the surface, also the `PasteReferenceLayer` function isn't unsafe

2023-01-25 20:50 UTC, flabbet requested changes
Drag n drop image into layers window works only once per document, if you undo after applying transform to first pasted image

2023-01-25 20:50 UTC, flabbet commented on src/PixiEditor/ViewModels/SubViewModels/Main/ClipboardViewModel.cs
> +    [Command.Basic("PixiEditor.Clipboard.PasteAsNewLayer", true, "Paste as new layer", "Paste from clipboard as new layer", CanExecute = "PixiEditor.Clipboard.CanPaste", IconPath = "$PixiEditor.Clipb
Paste as new layer doesn't work

2023-01-25 20:50 UTC, flabbet commented on src/PixiEditor/ViewModels/SubViewModels/Main/DebugViewModel.cs
> +        Mouse.OverrideCursor = null;
xD

2023-01-25 20:50 UTC, flabbet commented on src/PixiEditor/Views/Dialogs/CommandDebugPopup.xaml
> +                              CloseCommand="{x:Static SystemCommands.CloseWindowCommand}"
Close button doesn't work, probably you forgot to initialize system commands for this window

2023-01-25 20:50 UTC, flabbet commented on src/PixiEditor/Views/Dialogs/CommandDebugPopup.xaml
> +﻿<Window x:Class="PixiEditor.Views.Dialogs.CommandDebugPopup"
Searchbar of command would be nice too, but it's no must

2023-01-27 21:05 UTC, flabbet requested changes
1. Open PixiEditor
2. Create new Document
3. Have copied image in clipboard
4. Ctrl + V
5. Don't click apply transform
6. Ctrl + v again

2023-01-27 21:10 UTC, flabbet commented
The rest of issues, seems to be fixed

2023-01-29 17:01 UTC, flabbet approved these changes
Yup, seems to be fixed

2023-01-29 23:55 UTC, Equbuxu commented
The opacity slider infinite loading problem is still there, but it seems like that's the only issue

2023-02-01 19:43 UTC, Equbuxu requested changes
After dragging the opacity slider you can no longer change opacity by clicking the slider body. But hey, at least it doesn't cause infinite loading anymore

2023-02-03 20:18 UTC, Equbuxu approved these changes

2023-02-03 21:22 UTC, merged