Clear Selection when single point is selected. Add CloseWindow/MaximiseWindow Shortcuts, add CloseWindow to File Menu
PixiEditor/PixiEditor pull request #46
Opened 2020-09-12 21:49 UTC by PolarJunction

## Pull Requests

### Modifications
* Updated SelectTool to clear the selection when a single point is clicked. The tool feels much more natural to clear by not selecting anything. It would be nice in the future to also clear the selection when we don't click on the canvas.
* Added Exit (CloseWindow) command to the File Menu, I think most applications have the ability to exit this way.
* Added MaximiseWindow (F11) shortcut.

![image](https://user-images.githubusercontent.com/19593942/93005547-e0228d80-f549-11ea-8cdc-9a024bb5d662.png)

### Testing

#### Select Tool
* Create a new file
* Make a selection of a group of points
* Select a single point
* **VERIFY** that the selection is cleared.

#### Shortcuts
* Create a new file, and add some pixels
* Select File>Exit
* **VERIFY** that the CloseWindow confirmation is displayed
* Press cancel, then reduce the size of the Window
* Press F11
* **VERIFY** that the Window is maximized.

#### Test Cases

* All test cases passing, noticed intermittent failures with the ClipboardControl tests.

2020-09-13 09:36 UTC, flabbet requested changes
About the Maximize shortcut, I think it would make more sense if it would toggle the actual fullscreen, that covers the Windows taskbar too. To do that you will need to change the max-height probably, check `MainWindow.cs`.

2020-09-13 09:36 UTC, flabbet commented on PixiEditor/Views/MainWindow.xaml
> +                    <MenuItem Header="_Exit" Command="{x:Static SystemCommands.CloseWindowCommand}" />
One small thing I would add, a `<Separator />` above the Exit menu option.

2020-09-13 09:37 UTC, flabbet commented
Everything else good 💯

2020-09-16 15:22 UTC, PolarJunction commented
Added separator to exit menu.

Wasn't able to add Full Screen toggle. the following options are required to be set to achieve Full Screen:

-  MaxHeight = SystemParameters.PrimaryScreenHeight;
-  ResizeMode = ResizeMode.NoResize;
-  WindowState = WindowState.Maximized;
-  WindowStyle = WindowStyle.None;

Recommend a separate issue is raised to create a toggle command and replace the F11 functionality.

2020-09-16 17:43 UTC, flabbet approved these changes

2020-09-16 17:43 UTC, merged