Reference layer and general improvements
PixiEditor/PixiEditor pull request #462
Opened 2023-02-13 19:24 UTC by CPKreuz

- Fixed the debug build configuration (which has already been fixed on master)
- Fixed how CommandDebugPopup evaluates icons
- Made reference layer as top most visible while transforming with transparency
- Implemented making reference the top most layer
- Added file search result for importing as reference layer
- Command Search now ignores whitespaces

2023-02-13 20:22 UTC, flabbet commented
Request to change the look to sth like this 
![Copied](https://user-images.githubusercontent.com/25402427/218566533-d2f446bf-c312-4be1-80d7-e4329b316d1b.png)

2023-02-15 21:04 UTC, flabbet requested changes

2023-02-15 21:04 UTC, flabbet commented on src/PixiEditor.ChangeableDocument/Changes/Drawing/SelectionToMask_Change.cs
> +internal class SelectionToMask_Change : Change
This should be in Select menu as well

2023-02-15 22:10 UTC, CPKreuz commented
Note to future self: Make sure the filter commands are shown in keybind settings

2023-02-16 17:27 UTC, flabbet approved these changes

2023-02-16 17:29 UTC, merged