Right click mode and other improvements
PixiEditor/PixiEditor pull request #537
Opened 2023-05-27 14:42 UTC by CPKreuz

* Added crop to selection command #488 
* Changed default export shortcut to Ctrl + E
* Updated Discord's background color in HelloTherePopup to the current blurple
* Fixed open appdata commands
* Added right click mode

The implementation for right click mode is probably not the best and buggy when bringing the mouse cursor out of the viewport while drawing

2023-05-29 15:20 UTC, flabbet commented
![image](https://github.com/PixiEditor/PixiEditor/assets/25402427/34362f82-9cee-4019-826a-fdc632dc435c)

2023-05-29 20:30 UTC, Equbuxu submitted a review, later dismissed

2023-05-29 20:30 UTC, Equbuxu commented on src/PixiEditor/Models/DocumentModels/Public/DocumentOperationsModule.cs
> +        if (Document.SelectionPathBindable.IsEmpty)
would be nice to check for TightBounds having W > 0 and H > 0 too, so that the change doesn't fail validation

2023-05-29 20:30 UTC, Equbuxu commented on src/PixiEditor/Views/MainWindow.xaml.cs
> +            DataContext.ToolsSubViewModel.ActiveTool is ShapeTool)
I'd argue that the context menu should be fully disabled on other modes, instead of it being based on the tool (open for discussion tho)

2023-06-16 21:23 UTC, flabbet requested changes
Erase mode should erase in brightness tool
Selection tools should always have context menu, brightness tool should darken on right click with secondary color mode

2023-06-17 17:04 UTC, flabbet requested changes
There shouldn't be a tool that doesn't have right click action. Zoom, rotate, move and eraser tool should also have context menu for right click for secondary color mode. On Erase mode, they should erase (I guess it also makes sense for Eraser, for the sake of muscle memory).

Second thing is no space between label and dropdown 
![image](https://github.com/PixiEditor/PixiEditor/assets/25402427/9a38dbe1-c623-4974-85bd-c4f8322e3c06)

2023-06-17 17:45 UTC, flabbet requested changes
No hover in dropdown 
![image](https://github.com/PixiEditor/PixiEditor/assets/25402427/87e5b359-4963-4fb7-ac2b-e1f8e13a4249)

Brightness tool opens context menu and darkens on secondary color mode

Color picker opens context menu on erase mode
Eraser opens context menu on erase mode (should erase on both)

2023-06-18 17:54 UTC, flabbet requested changes
(Use erase mode) Select Rectangle Tool -> Select Eraser tool -> Erase with right click

Expected behavior: Eraser tool stays selected
Actual behavior: Selected tool gets switched back to rectangle tool.

Except that everything else seems good

2023-06-20 16:36 UTC, flabbet requested changes

2023-06-20 16:36 UTC, flabbet commented on src/PixiEditor.ChangeableDocument/Changes/Selection/SelectEllipse_UpdateableChange.cs
> +        documentConstraint.AddRect(new RectI(VecI.Zero, target.Size));
You can easily omit this constraint by resizing canvas, I doubt it's a problem though. It applies to all constraints you made

2023-06-24 11:56 UTC, CPKreuz commented on src/PixiEditor/Views/UserControls/Layers/FolderControl.xaml
> +                                d:Text="New Folder" FontSize="14"
The EditableTextBlock's both have 14

The opacity/blending mode text are actually inconsistent

2023-06-24 15:07 UTC, flabbet approved these changes
😘

2023-06-24 15:09 UTC, merged