Invalid file import
PixiEditor/PixiEditor pull request #95
Opened 2020-11-22 14:54 UTC by flabbet

Fixes #67

 1. Clearly describe changes, as detailed as possible
 2. If possible, show examples of usage
 3. Ensure any install or build dependencies are removed before the end of the layer when doing a build.
 4. Make sure all tests are passing.

1. Added `CorruptedFileException` which is thrown by `ImportImage` and `ImportDocument`. Wrapped `Open()` method with try and catch, whenever `CorrupetFileException` is thrown, error MessageBox is shown to the user. Also changed framework version to .NET 5.
2. Just rename any non-image file to .jpg, .png, or .pixi extension and try to open it in PixiEditor.
3. Yup
4. Yup

2020-11-22 14:54 UTC, flabbet commented
@CPKreuz Do you mind reviewing?

2020-11-22 17:57 UTC, CPKreuz commented
Will do tomorrow

2020-11-23 15:36 UTC, CPKreuz requested changes

2020-11-23 15:36 UTC, CPKreuz commented on PixiEditor/ViewModels/ImportFilePopupViewModel.cs
> +                    BitmapImage bitmap = new BitmapImage(new Uri(path));
After hex editing a image file it threw an `FileFormatException` with the message 'The image format is unrecognized.'

2020-11-23 15:56 UTC, CPKreuz approved these changes
Seems to work now

2020-11-23 16:00 UTC, merged